backend:
  name: github
  repo: City-Bureau/documenters-field-guide

# publish_mode: editorial_workflow

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "before-you-begin"
    label: "Before you begin"
    folder: "src/content/before-you-begin"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Order, name: order, widget: number }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "on-assignment"
    label: "On assignment"
    folder: "src/content/on-assignment"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Order, name: order, widget: number }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "resources"
    label: "Resources"
    folder: "src/content/resources"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Order, name: order, widget: number }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "contact-page"
    label: "Contact"
    files:
      - file: "src/content/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "main"
    label: "Home Page"
    files:
      - file: "src/content/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: "Intro List",
              name: introlist,
              widget: list,
              field: { label: "Item", name: item, widget: markdown },
            }
          - {
              label: Questions,
              name: questions,
              widget: list,
              fields:
                [
                  { label: Question, name: question, widget: string },
                  { label: Answer, name: answer, widget: markdown },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
