backend:
  name: github
  repo: City-Bureau/documenters-field-guide
  branch: main

# publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "main"
    label: "Main Content"
    files:
      - file: "src/content/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - label: Template
            name: templateKey
            widget: select
            options:
              - label: Index
                value: index-page
            default: index-page
          - {
              label: "Before you begin",
              name: beforeyoubegin,
              widget: list,
              field: { label: "Item", name: item, widget: markdown },
            }
          - {
              label: "On assignment",
              name: onassignment,
              widget: list,
              field: { label: "Item", name: item, widget: markdown },
            }
          - {
              label: Payment,
              name: payment,
              widget: list,
              fields:
                [
                  { label: Question, name: question, widget: string },
                  { label: Answer, name: answer, widget: markdown },
                ],
            }
          - {
              label: Questions,
              name: questions,
              widget: list,
              fields:
                [
                  { label: Question, name: question, widget: string },
                  { label: Answer, name: answer, widget: markdown },
                ],
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - label: Template
            name: templateKey
            widget: select
            options:
              - label: Page
                value: page-template
              - label: Category
                value: category-template
              - label: Ignore
                value: ignore
            default: page-template
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/content/terms-and-conditions/index.md"
        label: "Terms and Conditions"
        name: "terms-and-conditions"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - label: Template
            name: templateKey
            widget: select
            options:
              - label: Page
                value: page-template
              - label: Category
                value: category-template
              - label: Ignore
                value: ignore
            default: page-template
          - { label: Order, name: order, widget: number }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "before-you-begin"
    label: "Before you begin"
    folder: "src/content/before-you-begin"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Template
        name: templateKey
        widget: select
        options:
          - label: Page
            value: page-template
          - label: Category
            value: category-template
          - label: Ignore
            value: ignore
        default: page-template
      - { label: Order, name: order, widget: number }
      - {
          label: Image,
          name: image,
          widget: image,
          default: "/img/default.png",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "legal-reference"
    label: "Legal Reference"
    folder: "src/content/legal-reference"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Template
        name: templateKey
        widget: select
        options:
          - label: Page
            value: page-template
          - label: Category
            value: category-template
          - label: Ignore
            value: ignore
        default: page-template
      - { label: Order, name: order, widget: number }
      - {
          label: Image,
          name: image,
          widget: image,
          default: "/img/default.png",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "on-assignment"
    label: "On assignment"
    folder: "src/content/on-assignment"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Template
        name: templateKey
        widget: select
        options:
          - label: Page
            value: page-template
          - label: Category
            value: category-template
          - label: Ignore
            value: ignore
        default: page-template
      - {
          label: Image,
          name: image,
          widget: image,
          default: "/img/default.png",
        }
      - { label: Order, name: order, widget: number }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "resources"
    label: "Resources"
    folder: "src/content/resources"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - label: Template
        name: templateKey
        widget: select
        options:
          - label: Page
            value: page-template
          - label: Category
            value: category-template
          - label: Ignore
            value: ignore
        default: page-template
      - { label: Order, name: order, widget: number }
      - {
          label: Image,
          name: image,
          widget: image,
          default: "/img/default.png",
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "contact-page"
    label: "Contact"
    files:
      - file: "src/content/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - label: Template
            name: templateKey
            widget: select
            options:
              - label: Page
                value: page-template
              - label: Category
                value: category-template
              - label: Ignore
                value: ignore
            default: page-template
          - { label: "Body", name: "body", widget: "markdown" }
