name: Deploy
on:
  push:
    branches:
      - main

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_STORAGE_ACCOUNT: documentersguide
  AZURE_CDN_PROFILE: documentersguide
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/setup-node@v1
        with:
          node-version: "11.x"

      - run: yarn

      - run: yarn build

      - run: make deploy
